### ISSUE TITLE
Installation package only has TrueType fonts

### ISSUE THREAD

**Issue by basus** [CatharsisFonts/Cormorant#11]
The Cormorant Install 2.0 Zip file seems to only have TrueType (.ttf) files, and not the OpenType files. From reading the Cormorant Behance page it seems like more features are available via the OpenType files.

**Comment by CatharsisFonts** [comment]
Dear Shrutarshi, 
don't worry, the TrueType files offer exactly the same OpenType features as the OpenType fonts, so you're not missing anything at all by using the TrueType fonts. I've favored the latter in my distributions because they seem to behave better in terms of hinting. On the other hand, I've been told that the OpenType fonts might be ever so slightly superior for printing at high quality. If you're interested in that, you can always download the OpenType font files from the repository.
Cheers, Christian

**Comment by basus** [comment]
Thanks much. I just pulled the repo and installed the OpenType fonts. I'll go ahead and close this.
