### ISSUE TITLE
Add otf version to the install package

### ISSUE THREAD

**Issue by RGB-es** [CatharsisFonts/Cormorant#12]
The Cormorant_Install_v2.1.zip file on the "release" folder only includes the ttf fonts: in order to obtain the otf fonts it is necessary to download the full source package. Maybe the "install" package could provide otf too? 
BTW, thanks for these amazing fonts!!!!

**Comment by CatharsisFonts** [comment]
Hi RGB-es, 

I've deliberately left out the OTFs from the release so that people wouldn't mistakenly install both the OTF and TTF files.  ;) The TTFs appear to behave better in terms of hinting, so I decided to favor those. If you want the OTFs, e.g. for printing purposes, the source package allows you to do so.

Cheers!
