### ISSUE TITLE
Some comments regarding Cyrillic glyphs

### ISSUE THREAD

**Issue by orthoxerox** [CatharsisFonts/Cormorant#14]
1. Cyrillic breve should be different from the Latin one. It should look like a telephone receiver, not like a crescent.
2. Cyrillic Л and Д look more Transitional than Garalde. Triangular versions would fit better and should be provided at least as stylistic alternates.
3. Cyrillic К and Ж could have ball terminals on their arms. This is a common feature of Cyrillic typefaces.
4. Cyrillic uppercase У has a very unusual leg shape. Ball terminals are much more common.

**Comment by CatharsisFonts** [comment]
Hi Orthoxerox,

(1) Good point, I'll change the shape.
(2) Triangular shapes seem to be almost entirely gone from present-day typography, and I've seen recommendations against using them (e.g., Leksandra's post on good Cyrillic; link below). I could add triangular shapes into the Garamond style, though.
(3) Ball terminals on К and Ж look extremely modern to me. Leksandra's page tells me there's no reason to use curly arms for those letters in a humanist font. BTW, my Latin and Cyrillic K's are not identical...  the Cyrillic shape is chosen so as to avoid clumping in Ж:
<img width="402" alt="screen shot 2016-04-24 at 11 58 10" src="https://cloud.githubusercontent.com/assets/13754106/14766694/00bfb9da-0a14-11e6-916e-7dd14f92f95d.png">
(4) I prefer a foot over a ball terminal here, given that the letter is supposed to «stand» on it. I suppose I could consider a ball terminal for the Garamond cut.

Leksandra's page: http://leksandra.livejournal.com/115861.html

Cheers, Christian

**Comment by orthoxerox** [comment]
(2) Well, Alexandra Korolkova definitely knows more about typesetting than I, but triangular shapes are still quite common in Old Style serif typefaces. I think both Ladoga (which is a very Old Style font) and Arno Pro have them.

(3) On [this page](http://kak.ru/columns/masterclass/a6619/) (written by Aleksandra's boss) you can see that both serif and ball terminals were used even back in 1704 for minuscules (see esp. [this](http://kak.ru/vimg/article/6346f7cd5de1f12632e73f28e4ac9770.gif) and [this](http://kak.ru/vimg/article/6e35dbcc74ef86edbc6496455162ffd9.gif)). If I remember correctly, Yuri Gordon also prefers ball terminals to serifs.

(4) It's your typeface and should reflect your own stylistic choices, of course. It's just that I have never seen a foot like this on a Cyrillic У in any other typeface. It's always either a ball or a gentle bend.

**Comment by orthoxerox** [comment]
I take my words back that I've never seen a У with a foot before. Trajan Pro 3 by Slimbach has one.

**Comment by orthoxerox** [comment]
Ok, I now have reasons to doubt my memory once again. I've checked several Venetian typefaces done by ParaType, and all of them have footed У and serifed к and ж. Garalde typefaces alternate between serifed and balled к and ж (Garamonds prefer balls), and practically all of them have balled У.

**Comment by orthoxerox** [comment]
Okay, sorry for multiple posts in a row, but I wanted to summarize my views.

1. Neither Venetian nor Garalde typefaces can have 100% natural Cyrillic letters, being invented before the typeface reform of Peter I. Even the best typeface will feel a bit like a castle in Indiana, no matter how authentic the construction process was. This is unavoidable. This also means they are less likely to be used for body text, especially Venetians.

2. Venetian Cyrillic typefaces tend to have a look of a stainless steel murderspider, so your К, У, Ж should definitely stay as they are in the *vulgaris* cut. Д and Л should be triangular by default. I might even dare to propose an И with sharp "elbows" to avoid excessive "picket fences" in "Вершинин" and "минимизация синиц".

3. The Garamond cut should be closer to the traditional Cyrillic typefaces to improve legibility, and that means moving closer to Caslon and later typefaces than to the real Garamond. К, У, Ж could get ball or flared terminals (well, У *should* get one), Д and Л can keep their modernized form in body text.

I feel I must add your font has one of the best Cyrillic glyphs among FOSS typefaces I've seen.

**Comment by CatharsisFonts** [comment]
Hi Orthoxerox

The thought that humanist serifs and Cyrillic are at odds with each other is very interesting — I've often had the impression that some aspects of Cyrillic reveal technical and geometric thinking at odds with the humanist pen logic (e.g., Ж and Я). If they were designed with modern serif logic in mind, then they make a lot more sense!

In my type design endeavors, though, I never let historical aspects get in my way. ;o) On one hand, I am just blissfully ignorant of most of the history of script and type design, having never gone through any sort of design school; on the other hand, I firmly believe in making fonts for the present and the future rather than for the past. Thus, I prefer to pick the elements that work best for my creative vision, regardless of whether they've ever appeared together in history.

Thus, for the default cut of Cormorant, I would prefer to keep the stainless-steel murderspider look (very accurate term!) for the capitals, which just fit the design intention behind Cormorant very well, as well as the trapezoid Д and Л, which strike me as the typographically superior forms. However, I'm happy to ensure that the Garamond cut contains a historically sound combination of forms. Would you rather have triangular Д and Л, or ball terminals there...? Judging from the Garamond name, I guess triangular would be more appropriate...  although I guess the ball terminals would be more desirable from a usage point of view? In any case, I could fit the style not represented by the Garamond cut into SS01 instead.

Here's my new breve; does it work?
<img width="116" alt="screen shot 2016-04-27 at 16 34 02" src="https://cloud.githubusercontent.com/assets/13754106/14855827/e1e0e5dc-0c95-11e6-8443-d15e50e94049.png">

BTW, I noticed a few missing kerning pairs in my Cyrillic. I'll have to go over it a bit more carefully. Unfortunately I currently can't export Cormorant because I'm getting a weird error message that haven't seen before (I believe it has to do with the Unicase export script). I'll try to fix that ASAP.

**Comment by orthoxerox** [comment]
Hello Christian.

[Ladoga by Viktor Kharyk](http://viktor-kharyk.livejournal.com/2261.html) has calligraphically correct Ж and Я. They look rather unusual, since the text instantly becomes written, rather than cast and printed. But every time you use Humanist serif typeface to print someting in Russian, Serbian or Bulgarian you are making a bold statement anyway. You might get away with printing Umberto Eco or G.R.R. Martin in Garamond or Jenson, but Stieg Larsson would look unbearably pretentious.

Trapezoidal Д and Л are not necessarily better typographically. They are more modern and are easier to kern, but triangular versions won't look out of place in a display font either. If you prefer to keep the existing versions, then I think the Garamond cut should get ball terminals for КЖУ.

I think the neck of the breve should have a bit more girth. I understand that Cormorant is a high contrast font with tall diacritics, so I won't say it *must* have more girth. I'd rather you asked a few more people (preferably desginers and not artistically challenged engineers like me).

Cheers.

**Comment by CatharsisFonts** [comment]
Hi Orthoxerox, 

I suppose if Cyrillic Garalde always looks artificial to some degree, that gives me all the more artistic freedom, since I don't feel obliged to strive for some unattainable goal.  ;o)

Meanwhile, I've started by implementing triangular forms for SS01, since I figure that's the easier of the two jobs. How is it working out? I like the looks of it, but I have to say the trapezoidal forms still make for a more harmonious look and feel overall.

<img width="700" alt="trapde" src="https://cloud.githubusercontent.com/assets/13754106/14935402/af5f50ca-0ed0-11e6-9492-11083a954398.png">

<img width="696" alt="trigde" src="https://cloud.githubusercontent.com/assets/13754106/14935405/b212d170-0ed0-11e6-87e9-2ac14b1d2210.png">

**Comment by orthoxerox** [comment]
Hi Christian, your letters look :+1:

Looks like ля will be a hard glyph pair to kern, though.

**Comment by CatharsisFonts** [comment]
Thanks!
That pair actually appears in the text above:
<img width="467" alt="screen shot 2016-04-30 at 15 42 23" src="https://cloud.githubusercontent.com/assets/13754106/14936279/3ec192fa-0eea-11e6-9930-4060e8456559.png">
I don't think it looks too bad. I suppose I could make up a contextual alternate for я to appear after letters with diagonally extended feet.

**Comment by CatharsisFonts** [comment]
I also changed the и design for the Garamond cut. I think it does help restore the sense of continuity that was partially lost with the departure from the trapezoidal shapes.
<img width="972" alt="screen shot 2016-04-30 at 16 23 18" src="https://cloud.githubusercontent.com/assets/13754106/14936557/0e155f5a-0ef0-11e6-9c2e-1d2090d29299.png">

**Comment by orthoxerox** [comment]
Very nice. Have you thought about adding Serbian/Bulgarian letterforms?

**Comment by CatharsisFonts** [comment]
I do have those already (SS10).

**Comment by orthoxerox** [comment]
Oh, I must've missed them somehow, sorry.

**Comment by CatharsisFonts** [comment]
BTW, the latest version available on the coming Friday is going to be ingested into Google Fonts, so I need to wrap things up until then. 

Would you be willing to help with that? Most of all, I could use someone to test the fonts with Cyrlllic texts and look for missing kerning pairs and the like.

**Comment by orthoxerox** [comment]
Sure, should I just download the latest binaries off GitHub? I also checked out your Bulgarian letterforms and some are a bit weird (here's a good reference: http://cyrillicsly.com/post/87982259290/for-our-talk-at-atypi-we-were-looking-for-a-way)

- н, ш, щ, ь, ч haven't lost their Russian capital-like upper serifs
- ь and ъ haven't lost their bottom serifs
- з should have a descender
- italic *в* looks more upright than other letters

Serbian italic was in ss09, btw, and it looks fine to my non-Serbian eyes.

**Comment by CatharsisFonts** [comment]
Thanks, I've corrected those now.
<img width="855" alt="screen shot 2016-05-01 at 00 19 44" src="https://cloud.githubusercontent.com/assets/13754106/14938867/a8c4b090-0f32-11e6-9342-e706f9aef049.png">

Yes, you can get the latest Glyphs-files from the repository (the issues are now out of date). I just committed the newest version with the corrected Bulgarian.

**Comment by CatharsisFonts** [comment]
BTW, is this Bulgarian /ve better?
<img width="335" alt="screen shot 2016-05-02 at 20 34 45" src="https://cloud.githubusercontent.com/assets/13754106/14963803/af5c047a-10a5-11e6-9db5-e5e13120257f.png">

**Comment by orthoxerox** [comment]
I was talking about italic в, but I think the bowed back looks better than the straight.

**Comment by CatharsisFonts** [comment]
Really? The bowed one looks gooey and out of place to me amidst the Roman-style characters.

**Comment by orthoxerox** [comment]
The back can't be 100% straight. Is there a Latin letter where your stroke starts with a curve, then becomes straight and ends with another curve? f, t and j have only one transition, two transitions would require a scribe with robot hands. You could make the back straighter, but not making it completely straight.

To be honest, I don't like Bulgarian в, ж, з and ю in general. They are either calligraphically or historically dubious and their shapes are all about "more ascenders and descenders!".

**Comment by CatharsisFonts** [comment]
I see your point. I'll try a more vertical curve-back design.
I do appreciate the friendliness of Bulgarian lowercase, which is why I'm exporting it in Cormorant Infant. I suspect all the u- and n-shapes hinder rather than improve legibility. The ascenders also look rather haphazard to me — particularly the fact that ж and к both have an extender, which doesn't help distinguish them at all...

**Comment by orthoxerox** [comment]
Hello Christian,

Re: BGR. I don't find that u- and n-shapes hinder legibility, such letter shapes are relatively common even in Russia (though restricted to shopfronts, not body text), but I feel that words like шишки look like peasant rebels on the march with all the serifs.

I tried to print out some Pushkin using ss02 of Garamond Book, and it looks like pairs уд, лу etc need some attention. I made sure to enable kerning in Word, maybe it doesn't pick the settings correctly.

**Comment by CatharsisFonts** [comment]
Thanks for the feedback!

I actually built the kink into the soft/hard signs not because of William, but because it fits the style of /g and infant /a. But I understand if it looks out of place. I've made the bottom round now. 

I've also made an attempt at making м fit. Does that work?

As for the /g, I guess you meant the sharp corner? I've softened it up a little.

<img width="789" alt="screen shot 2016-05-04 at 00 23 12" src="https://cloud.githubusercontent.com/assets/13754106/15000233/9b8eb980-118e-11e6-90f9-9ac4bf4540ce.png">

As for kerning: I've done quite a bit of it in the last few commits. I think the pairs you mentioned are covered in my current version:
<img width="786" alt="screen shot 2016-05-04 at 00 25 55" src="https://cloud.githubusercontent.com/assets/13754106/15000250/d0fdadce-118e-11e6-8280-28bdbb2b7373.png">

As for the apices of the /и: Better?
<img width="341" alt="screen shot 2016-05-04 at 00 28 54" src="https://cloud.githubusercontent.com/assets/13754106/15000311/45e40f52-118f-11e6-810b-f40c66eca207.png">

**Comment by CatharsisFonts** [comment]
Actually, I see what you mean about /g now. I've redesigned Infant /a, /g, and /q — better? I think so! :grin: 
<img width="346" alt="screen shot 2016-05-04 at 01 17 07" src="https://cloud.githubusercontent.com/assets/13754106/15001300/ba046ef2-1196-11e6-821a-8e77422c8fac.png">

**Comment by orthoxerox** [comment]
:+1: I'll try and read some more with the new version.

**Comment by CatharsisFonts** [comment]
Awesome, thanks!
BTW, I tried out some ball terminals, and I really don't like them. Maybe I'm just bad at them... I think I'm going to stick to murderspiders for both cuts.  :grimacing: 
<img width="282" alt="screen shot 2016-05-04 at 14 23 39" src="https://cloud.githubusercontent.com/assets/13754106/15014072/fe58e020-1203-11e6-9196-f8f90bc26c91.png">

**Comment by CatharsisFonts** [comment]
Actually, would this make a better /em for Bulgarian? Or for the Garamond, for that matter...?
<img width="429" alt="screen shot 2016-05-04 at 14 50 49" src="https://cloud.githubusercontent.com/assets/13754106/15014674/b8ba9ce4-1207-11e6-9e1e-26813ddb7df9.png">

**Comment by orthoxerox** [comment]
I've actually been thinking about an м like that, I'll try it out later today.

Ball terminals need a double bend in the arm to look smart, if the look's too modern for you, then murderspiders everywhere is the way forward.

**Comment by CatharsisFonts** [comment]
That would be great, thanks. I just added a dedicated kerning class for the Garamond /em, that should improve things further.

Yeah, I think double bends would indeed look too modern.

**Comment by orthoxerox** [comment]
Hm, now I think the vertical stroke of р is too thick (at least in the book cut), and the ball terminal of л is too prominent, it's like it's trying to trip someone (the reader?). р aside, ss02 looks fabulous, ду looks particularly great.

If you want some more nitpicking, then б feels a bit too large in body text. The tongue might be fine for the display cut, but it is too flamboyant for the book cut.

I also finally checked out the italic font. *д* has the same flamboyancy problem with its tongue as б has in roman. It usually is an integral part of the right stroke and doesn't have a hump, it goes downwards right from the start. For some reason, *б*'s tongue feels natural in italic.

**Comment by CatharsisFonts** [comment]
Thanks for your attention to detail!  Indeed, the /p's stem was two units thicker than the /n's for some reason (this also affected /b/d/q in the Latin). Fixed it. Is this ball terminal on /л better? (Bottom is new)
<img width="272" alt="screen shot 2016-05-05 at 01 59 29" src="https://cloud.githubusercontent.com/assets/13754106/15032814/0a33bf44-1265-11e6-8410-2a53911b7fc0.png">
I'll have to deal with /б and cursive /д tomorrow. Actually, I made the /д in response to a comment on Typedrawers:
http://typedrawers.com/discussion/comment/14682/#Comment_14682
What's your take on that?

Do you think I can keep the architecture of /б in the Garamond cut and just reduce its size a bit?

**Comment by orthoxerox** [comment]
I can't tell until I look at it, sorry Christian. To me б looked fine at display sizes, but in body text it was too big.

*д* shown by Alexander has one important difference from your final result: its tongue is not a separate stroke that is attached to *o*. Your previous *д* had this property as well.

**Comment by CatharsisFonts** [comment]
Hi Orthoxerox, 

how about this slightly narrower and less flamboyant /be-cy.ss02 (right-hand side)?
<img width="365" alt="screen shot 2016-05-05 at 18 46 43" src="https://cloud.githubusercontent.com/assets/13754106/15050059/dc637d7e-12f1-11e6-8fd2-c7f1630b4af2.png">
Now to figure out that cursive /de-cy...

**Comment by orthoxerox** [comment]
Hello Christian,

р looks good now, but it feels like ороророророро is not kerned correctly.

б doesn't jump out that much any more.

л is good as well.

I can't bring myself to like that *д*, though...

**Comment by CatharsisFonts** [comment]
Hi Orthoxerox,

I guess that's because my /er-cy has a flat top serif, which appears somewhat less space-consuming than the angled serif...?  In any case, I've reduced the left sidebearing just a bit. 

Is this /de-cy better? I can't help thinking of a rat's tail... do you have any other suggestions?
<img width="387" alt="screen shot 2016-05-06 at 01 12 58" src="https://cloud.githubusercontent.com/assets/13754106/15060162/5c0b2190-1328-11e6-916e-5693a89652ae.png">

Thanks for catching the missing kerning, those were really bad!

BTW, my submission deadline has been extended to Monday, so it's not quite as last-minute as it used to be.

**Comment by orthoxerox** [comment]
There's nothing wrong with a rat's tail. I've made this album of Adobe's and ParaType's old style serifs to showcase several possible *д*s, and most have a tapering tail:

http://imgur.com/a/YzeuJ

**Comment by CatharsisFonts** [comment]
OK, I'm keeping the rat's tail, I've grown to like it. ;o)

**Comment by orthoxerox** [comment]
You can call me orthoxerox with a lowercase "o" in the fontlog if you're fine with pseudonyms.

**Comment by CatharsisFonts** [comment]
Fair enough. Thanks for all the help, it's been tremendously useful!
