### ISSUE TITLE
localised BGR features

### ISSUE THREAD

**Issue by alexeiva** [CatharsisFonts/Cormorant#18]
Hi Christian, 
Congratulations with your release. 
Your detailed attention to Cyrillic localised features (BGR, SRB) across the family is touching.

May I point out some confusion in the Bulgarian Cyrillic:

Green — correct
Red — incorrect / unconventional
Yellow — the spacing too tight

1.uni0422 should be 'T',  uni0422.loclBGR should be 'm'
<img width="578" alt="screen shot 2016-06-16 at 07 38 10" src="https://cloud.githubusercontent.com/assets/16634089/16116719/82752e72-339c-11e6-9230-3bd7b50e6aeb.png">

2. Using the Latin lowercase 'm' for the Cyrillic М — it is mixed-up with Bulgarian or handwritten form of 'T'
<img width="683" alt="screen shot 2016-06-16 at 07 38 28" src="https://cloud.githubusercontent.com/assets/16634089/16116721/827fccb0-339c-11e6-9ab0-3bce4849cef4.png">

3. The ascender difference is unconventional. Yellow — spacing looks very tight. 
<img width="573" alt="screen shot 2016-06-16 at 07 39 33" src="https://cloud.githubusercontent.com/assets/16634089/16116720/827fb946-339c-11e6-9d2c-30f09be96cc8.png">

Best, 
Alexei

**Comment by CatharsisFonts** [comment]
Hi Alexei, 
you are talking about the Unicase fonts, right? This is due to a bug in how Glyphs treats glyph replacement custom parameters. The small-caps /te-cy.sc contains the Latin /t.sc as a component, and when I replace /t.sc with /t.sc.ss05 while exporting the Unicase fonts, the same change happens in /te-cy.sc, although it is not intended. You can use the default Cormorant fonts with the SMCP and SS05 features switched on to see what the Unicase fonts _should_ look like. 

That's also the reason why you get this weird uni044B.sc — the export code replaced one of the two components but not the other. Rest assured I've never drawn an uneven ы in my source file. ;)

Of course, I can avoid this error now by unlinking /te-cy.sc from /t.sc, but that's annoying because if I ever change /t.sc I'll have to remember to propagate the changes to /te-cy.

Thanks for reporting these!

**Comment by alexeiva** [comment]
Christian, 
Thanks for the detailed insight. What a strange glyphs bug. 

I spotted this error on the new google fonts website:
https://fonts.google.com/specimen/Cormorant+Unicase?subset=cyrillic&query=cormorant

Google shows the default version, and not the ss05 feature, so it is misleading for 
potential Cyrillic font user. 

<img width="364" alt="screen shot 2016-06-17 at 09 31 59" src="https://cloud.githubusercontent.com/assets/16634089/16152212/b84c1858-346e-11e6-980b-fdb96084edc8.png">
<img width="1031" alt="screen shot 2016-06-17 at 09 33 06" src="https://cloud.githubusercontent.com/assets/16634089/16152215/ba4469d0-346e-11e6-9c44-d19fd8f16cd6.png">

**Comment by CatharsisFonts** [comment]
Are you talking about the /em-cy? It looks consistently wrong in both your screenshot and GF...  I guess I'm just going to de-link all those letters as a workaround for the time being. Won't help the GF version, of course.

**Comment by alexeiva** [comment]
Yes, that's right. I downloaded the file from GF to make the glyphs screenshot, since there wasn't a source file for the unicase cut.

Cc @schriftgestalt @mekkablue

**Comment by schriftgestalt** [comment]
I added a "Decompose Glyphs" parameter. It will be applied before the "Rename Glyphs" parameter.

**Comment by CatharsisFonts** [comment]
Awesome, thanks Georg!  😁

**Comment by alexeiva** [comment]
Great, Looking forward to it, Georg
Was this the script used for generation?
https://github.com/schriftgestalt/Glyphs-Scripts/blob/master/Make%20Unicase%20Font.py

**Comment by CatharsisFonts** [comment]
No, I'm using custom scripts I originally adapted from a different script that Mekkablue wrote to export the Upright Cursive version of Traction. They're actually in the repository:

https://github.com/CatharsisFonts/Cormorant/tree/master/4.%20Glyphs%20Source%20Files/Cormorant%20Glyphs%20Scripts

**Comment by CatharsisFonts** [comment]
The Decompose Glyphs custom parameter is out, so the problem should be fixed in the newest commit. 😁

**Comment by CatharsisFonts** [comment]
While the bug persists in Glyphs, I have meanwhile figured out how the Decompose Glyphs custom parameter works, so that should be fine now...
