### ISSUE TITLE
Cormorant Infant oldstyle and lining figures

### ISSUE THREAD

**Issue by jiveemail** [CatharsisFonts/Cormorant#34]
The oldstyle figures in Cormorant Infant appear to be taller than the lining, and ss02 seems to provide a small-caps style letter I ('eye') for the numeral one with what look like the taller 0, [2-9].

**Comment by CatharsisFonts** [comment]
This is an unwanted side effect of glyph replacement in Glyphs. My script replaces the default (oldstyle) figures of Cormorant with the lining figures in Cormorant Infant, but Glyphs insists on also replacing the latter with the former. 

It shouldn't matter, though, since Cormorant Infant is a spin-off font meant only to be used on OpenType-ignorant applications. In applications with good OpenType support, you can just use the default Cormorant fonts and pick all the OpenType features you want. All features should work as intended there.

**Comment by jiveemail** [comment]
Understood. Thank you.

**Comment by jiveemail** [comment]
Christian,

Thank you so much for the (extremely) prompt reply.

I’ll revisit trying to get the right combination of features with the base font. I’m working on my resume, and am looking for a capital W without crossed arms, a non-schoolbook lowercase a, and proportional lining figures, both/all in InDesign, on the web, and in Word (still required by primitive HR departments.)

I’m a software engineer, and have been slowly learning the finer points of typography and design.

I really like your typeface, and the presentation and philosophy in providing it, and truly appreciate your contribution.

I hope

Sincerely,

Hal Brown
Corvallis, OR, USA

On May 23, 2017, at 11:18 AM, Christian Thalmann <notifications@github.com<mailto:notifications@github.com>> wrote:


This is an unwanted side effect of glyph replacement in Glyphs. My script replaces the default (oldstyle) figures of Cormorant with the lining figures in Cormorant Infant, but Glyphs insists on also replacing the latter with the former.

It shouldn't matter, though, since Cormorant Infant is a spin-off font meant only to be used on OpenType-ignorant applications. In applications with good OpenType support, you can just use the default Cormorant fonts and pick all the OpenType features you want. All features should work as intended there.
