### ISSUE TITLE
Cormorant Infant: Cyrillic letter "i with grave" is different

### ISSUE THREAD

**Issue by fingli** [CatharsisFonts/Cormorant#40]
In some variants of C.I. the letter "Ѝ" appears like it is from different font. Actually it has to look alike the regular letter "И" but stressed. I'm applying screenshot and source to Wikipedia for reference https://en.wikipedia.org/wiki/I_with_grave_(Cyrillic). 
Lower letter ѝ in Italic and BoldItalic are fine, the others not (red dots). 

![a1](https://user-images.githubusercontent.com/420475/36117708-4e463c56-1043-11e8-9d40-3e3805287ca5.PNG)

**Comment by CatharsisFonts** [comment]
Dear Yulian,

I believe I know what happened. It's a consequence of an absurd «feature» of Glyphs that has caused me trouble before. These glyphs actually look normal in Cormorant Infant... the problem is that you have loclBGR activated, and when Glyphs promoted the .loclBGR into the default glyph slots, _it also stored the original glyphs in the .loclBGR slots_. Your easiest solution right now is to either switch of localization, or to use the default Cormorant font and activate the Infant style through stylistic sets.

I should definitely look for a more comprehensive solution to that problem, though. I thought I had solved it by removing the locl feature from the Infant fonts, but apparently it hasn't worked...?

Are you using the newest version of Cormorant?

**Comment by fingli** [comment]
I'm using version 3.504 - the current one. The screenshot in the first post was from MS Word. I tried with GIMP, it renders font properly. Unfortunately I need C.I. for MS Word and Publisher mostly. 
The screenshot is from GIMP
![3](https://user-images.githubusercontent.com/420475/36272720-021aaa3e-128b-11e8-8969-89ee9babafde.PNG)

**Comment by CatharsisFonts** [comment]
Is the issue resolved by now?

**Comment by fingli** [comment]
**In LibreOffice everything is perfect**. In MS Word 2016 the small letter "ѝ" is still inconsistent with the regular form "и" but only in Infant version, in the other Cormorant fonts are OK .
Font version 3.601
Screenshots attached.
![LO](https://user-images.githubusercontent.com/420475/56867760-ed40ea00-69f1-11e9-9335-535f120b54fa.png)
![W](https://user-images.githubusercontent.com/420475/56867762-f2059e00-69f1-11e9-9251-169b893e740c.png)

**Comment by CatharsisFonts** [comment]
I've checked my files, and it seems /iigrave-cy/ was somehow missing from the SS10 stylistic set. I've added it. Can you check with the newest commit?

**Comment by fingli** [comment]
Great. The newest version is perfect. 
Thank you for the good work. 

![ci1](https://user-images.githubusercontent.com/420475/56890124-40ae4900-6a81-11e9-8923-18e206c37fe9.png)

**Comment by CatharsisFonts** [comment]
Sorry for the inordinately long wait! :P
