### ISSUE TITLE
Ligature fi and fl problems in Cormorant Infant

### ISSUE THREAD

**Issue by prestonpdx** [CatharsisFonts/Cormorant#46]
_I am using your Cormorant Infant and Barlow Semi Condensed fonts in a print book that I am publishing. I am very happy with both fonts, with one exception. The ligatures _fi_ and _fl_ often cause problems: an extra space later in the word or two letters overlapping. Sometimes the word looks perfectly good but the spelling checker flags it because it is broken in the middle.

Is there any solution to these problems as far as you know? I am using the fonts in Adobe InDesign software. I have  tried turning off ligatures in InDesign, but this doesn't help.

Here are some samples:
![capture6](https://user-images.githubusercontent.com/14043921/47685225-0677f380-db93-11e8-9980-ca2c68ad4067.PNG)
![capture2](https://user-images.githubusercontent.com/14043921/47685226-0677f380-db93-11e8-8136-787d6376736e.PNG)
![capture5](https://user-images.githubusercontent.com/14043921/47685227-0677f380-db93-11e8-9662-a4f668d86229.PNG)

 _

**Comment by CatharsisFonts** [comment]
Dear Preston
First of all, thanks for using my fonts! 😬 
I just looked at the most recent instance of Cormorant Garamond in FontBook, and there it performs as expected:
<img width="459" alt="screen shot 2018-10-31 at 10 57 26" src="https://user-images.githubusercontent.com/13754106/47780521-d5670280-dcfb-11e8-982d-e25741e52dd5.png">
I notice your malfunctioning ligatures contain the «short» version of /f, though. This version is cycled in before tall glyphs by the CALT feature by default. The LIGA feature should recognize both /f and /f.short, though, and replace both with the pretty ligatures based on regular /f. I'm guessing your issue is due to an unintended interaction between the CALT and LIGA features. Maybe switch off CALT as a quick fix?
I see you don't get the /T_h ligature either. Strange.
I don't have Adobe InDesign, so I can't try it out myself. Maybe ask their tech support for help?
Does this not happen with any other fonts?
Cheers, Christian

**Comment by prestonpdx** [comment]
I have discovered that these "ligature" problems were in my text before I applied the Cormorant Infant font. That is, the font is not responsible for my problems; they existed even before I used the font.
