### ISSUE TITLE
Greek?

### ISSUE THREAD

**Issue by steko** [CatharsisFonts/Cormorant#6]
First of all congratulations for crafting this beautiful type!

I see you have been quickly adding Cyrillic recently so I hope you will be also adding Greek soon?

**Comment by CatharsisFonts** [comment]
Dear Stefano,

I'm not sure... Cyrillic is comparatively easy, since its characters feel at home in a humanist serif face. I find it surprisingly hard to wrap my head around the Greek lowercase; its distribution of thick and thin strokes just doesn't make sense to me. I guess that's because it's meant to be hand-written with a paintbrush rather than with a broad-nib pen? 

In any case, I've made four Greek letters for Cormorant so far, since they were part of the Adobe Latin 4 package:

![screen shot 2015-09-22 at 0 47 31](https://cloud.githubusercontent.com/assets/13754106/10007189/8a2fe2bc-60c3-11e5-8c49-23127275c86c.jpg)
I think they look pretty ridiculous, especially in the Bold. If I'm to add full Greek support to Cormorant, I need to figure out the logic of its lowercase first. Can you help me with that?

Cheers, Christian

**Comment by steko** [comment]
Dear Christian,
thank you for clarifying the situation with Greek. I didn't know about the difference you mention of paintbrush vs broad-nib pen (and that is a very interesting distinction). I'm not sure how I could help you, I'm an avid user of beautiful typefaces but I never created a font 😞

**Comment by skosch** [comment]
I don't think you'll be able to do that successfully—adapting the ductus and those strong, fine serifs of Cormorant to the Greek alphabet (and its lowercase in particular) without sacrificing much of the beauty of the Greek script.

Some have tried, more or less successfully; here is Andron for instance:

![Andron Greek](http://typophile.com/files/Greek_ABCD_6191.png)

... but a less anachronistic (and more visually pleasing, IMHO) reference is probably Slimbach's Garamond Premier Pro:

![GPP](http://luc.devroye.org/RobertSlimbach--GaramondPremierProGreek-1992-2004.png)

I highly recommend Gerry Leonidas' [notes](http://typefacedesign.tumblr.com/post/12141428611/preparation-for-greek-typeface-design). He's *the man* when it comes to Greek type.

Btw, a google search for "Greek penmanship" throws up some interesting stuff (some of which I remember from Typophile discussions from a few ~5 years ago), e.g.

![GPS](http://typophile.com/files/1835_PorsonYoung7w_6327_6585.jpg)

Then again, it's certainly nice to have Latin-esque Greek glyphs around for use in mathematical expressions. The samples you're showing above may look ridiculous as Greek qua Greek, but at least they don't look silly adjacent to Latin ones. You could provide *two* alphabets, or make a call which use case you deem more important: scientific texts/integration with Latin, or belletristic/authentic Greek texts (if the latter, I encourage you to consider designing non-bastardized uppercase letters as well, which are rare but awesome).
