### ISSUE TITLE
Comorant Garamond Incorrect path direction in 'e'

### ISSUE THREAD

**Issue by mrecord** [CatharsisFonts/Cormorant#69]
In Comorant Garamond, the crossbar on the 'e' has the wrong path direction and is showing holes in the letter.
It's visible in Mac Firefox and Safari, but not in Mac Chrome. (I didn't check in Windows).

Screenshot (from [this page](https://www.chengdugourmet2.com/)):

<img width="695" alt="Screen Shot 2022-09-02 at 8 49 14 AM" src="https://user-images.githubusercontent.com/13879228/188149932-be66cef1-4d16-4014-90bd-cf7ab349c837.png">

**Comment by CatharsisFonts** [comment]
Weird, I’ve never seen that before, even on pages using Cormorant Garamond (and there are many of those!). Are you using the Google Fonts version?

My computer is currently broken, unfortunately, so I can’t look into it right now. 

Cheers, Christian

**Comment by mrecord** [comment]
Yes, it's the Google Fonts version. 

Visible on the [specimen page](https://fonts.google.com/specimen/Cormorant+Garamond/glyphs) in 'e' and all components.
<img width="867" alt="Screen Shot 2022-09-02 at 9 13 38 AM" src="https://user-images.githubusercontent.com/13879228/188153730-a0f3bb8f-a9ed-43f9-a45c-60c70fa19699.png">

**Comment by CatharsisFonts** [comment]
Ok, that’s bad. I’ll look into it.

**Comment by kenmcd** [comment]
> In Comorant Garamond, the crossbar on the 'e' has the wrong path direction and is showing holes in the letter. It's visible in Mac Firefox and Safari, but not in Mac Chrome. (I didn't check in Windows).
> 
> Screenshot (from [this page](https://www.chengdugourmet2.com/)):
> 
> <img alt="Screen Shot 2022-09-02 at 8 49 14 AM" width="695" src="https://user-images.githubusercontent.com/13879228/188149932-be66cef1-4d16-4014-90bd-cf7ab349c837.png">

Are you using macOS 10.xx?
It has issues with rendering overlaps properly.

**Comment by CatharsisFonts** [comment]
Sorry for dropping the ball on this. I can't see anything wrong with Cormorant's /e.ss02/, which is used in Cormorant Garamond. I hope it's a rendering fault as proposed by kenmcd. 

<img width="476" alt="Screenshot 2022-11-22 at 22 37 56" src="https://user-images.githubusercontent.com/13754106/203426602-357111a5-5387-4af8-9c2e-09d66c1c3faf.png">

Any new insights from your part?

Cheers, Christian

**Comment by wavygecko** [comment]
The font files from Google Fonts appear fine for me, but the font files from this repository have the issue with the "e" — perhaps you could update the font files in this repository with the ones that are on Google?

**Comment by kenmcd** [comment]
> The font files from Google Fonts appear fine for me, but the font files from this repository have the issue with the "e" — perhaps you could update the font files in this repository with the ones that are on Google?

The fonts on Google Fonts have overlaps (like on the e above).
The fonts available here in the repo do not have overlaps.
So if you are seeing an overlap issue something else is wrong.

Exactly what font are you using? 
What operating system?
What application?
Please provide a screenshot.

**Comment by kenmcd** [comment]
OK. I see what happened.
The fonts in the repo were regenerated 8 months ago (May 6, 2022) by a GF rep using the GF tools.
The GF tools do not remove the overlaps.
So the fonts in the repo now have overlaps still in them.
Which is usually not the case for upstream repo fonts.

Previously the fonts were generated from the font developers' font editor and the overlaps were removed when the fonts were generated.
I have been looking at these older repo fonts which have no overlaps.
These are the older fonts without the overlaps:
[fonts.v3.614.(2021-10-20).from.master.zip](https://github.com/CatharsisFonts/Cormorant/files/10362209/fonts.v3.614.2021-10-20.from.master.zip)
So those should work for you.

But I am surprised you have an issue with overlaps in macOS 12.6 - I thought this overlaps issue was fixed in maxOS 11.

@CatharsisFonts Hi Christian,
You may want to regenerate the fonts with the overlaps removed.
Many users/applications still need overlaps removed.

**Comment by CatharsisFonts** [comment]
Very interesting! I suppose the GF tools should be updated to remove overlaps, then...?  (@davelab6)

**Comment by CatharsisFonts** [comment]
@kenmcd @wavygecko New commit is available.

**Comment by wavygecko** [comment]
I checked the new .otf files and they look resolved now. Thank you! 🙂
