### ISSUE TITLE
Triple "f" ligature

### ISSUE THREAD

**Issue by jenstroeger** [CatharsisFonts/Cormorant#8]
I am not sure this is common, but in German compound nouns with a triple "fff" can happen: Auspufffeuer, Schifffahrt (see attached image). There's no ligature for that one, right? Are there plans to add it, or does it not make sense because it helps separating the two nouns?

![schifffahrt](https://cloud.githubusercontent.com/assets/12053937/10118394/76f3cd1a-642b-11e5-9d11-b1de0397a073.jpg)

**Comment by grzegorzrolek** [comment]
Indeed, it is standard practice in German orthography to break ligatures at morpheme boundaries, as it is considered to make compound words easier to comprehend. To quote [Wikipedia on typographic ligatures](https://en.wikipedia.org/wiki/Typographic_ligature#Latin_alphabet) (which, by the way, gives _Schifffahrt_ as an example):

> Ligatures crossing the morpheme boundary of a composite word are sometimes considered incorrect, especially in official German orthography as outlined in the Duden. An English example of this would be ff in _shelf‌ful_; a German example would be _Schifffahrt_ (“boat trip”).

Here’s also an interesting example from [a message by Otto Stolz on the Unicode mailing list](http://www.unicode.org/mail-arch/unicode-ml/y2007-m11/0099.html):

> [In German], »auf·fliegen« has an fl-ligature (in professional typography), while it must not have an ff-, nor an ffl-ligature (in any typography that claims to be orthographically correct).

**Comment by jenstroeger** [comment]
Makes sense, thank you! So that's a “no” to the fff ligature then?

**Comment by CatharsisFonts** [comment]
I hadn't included an f_f_f ligature previously, since there is always a morpheme boundary between the second and third f, and the first two f's ligate just fine with the current model. Then again, the default LIGA feature replaces, e.g., /f/b indiscriminately with /f_b.liga, so there's not necessarily a reason to treat /f/f/f differently. 

Personally, I love ligatures and don't mind them being used across morpheme boundaries, so I think I'll implement /f_f_f. I've already drawn it, after all. ;o)

What I'd like to do is to implement a CALT feature that replaces /f before /b/f/h/l/k/þ with /f.short to avoid collisions where ligatures are switched off. Problem is, CALT is evaluated before LIGA, so /f/b turns into /f.short/b, which the automatic LIGA feature then no longer recognizes properly when both features are turned on. I'd have to expand the LIGA feature by things like "sub f.short b by f_b.liga;", which means I can't rely on automatic feature creation. Hmpf. Given that the fonts are basically finished, though, I suppose I could pull that off.

**Comment by CatharsisFonts** [comment]
Oh, hey, that wasn't all that difficult. :) I've implemented the changes in version 0.6, to be uploaded soon.
When you switch off LIGA, the CALT kicks in to make things presentable (although not necessarily pretty):

![screen shot 2015-09-26 at 23 35 53](https://cloud.githubusercontent.com/assets/13754106/10119994/0db5556c-64a8-11e5-830d-cb643859c01b.jpg)

Whereas with LIGA it gets really pretty, if not necessarily traditionally correct:
![screen shot 2015-09-26 at 23 39 42](https://cloud.githubusercontent.com/assets/13754106/10119997/20886508-64a8-11e5-9146-8fde7acfdede.jpg)
